### PR TITLE
Fix compiling on staging branch

### PR DESCRIPTION
**Pull request by Felanbird**
I believe this workaround change is causing your issue.

Related: https://github.com/Chatterino/chatterino2/pull/3664#issuecomment-1093846709 - I assume the `staged-release` branch you created was annotated.

### CODE REVIEW

**Comment by AnatoleAM** [comment]
Uuuhh i'm confused why it compiled before but it failed only now

**Comment by Felanbird** [comment]
🤷 maybe u didn't annotate the branch, but gh actions did it for you?

**Comment by AnatoleAM** [comment]
uh, perhaps, i am not actually sure what you mean by annotating the branch

**Comment by Felanbird** [comment]
Meant to say tag* but I'm not sure on it either actually. 🤔

**Comment by Felanbird** [comment]
`Annotated tags are created using the -a flag.
The difference between regular tag to annotated tag is that the annotated tag is like a commit, it contain the date, author and the message attached to it.`

thanks stackoverflow

**Comment by Felanbird** [comment]
If I'm understanding the stackoverflow answer, using `--tags` specifically in our use-case, seems to be a workaround to getting the correct info when a tag is not annotated, so that's the "reason" it was implemented on this repo, but when I attempted to use this logic on upstream pajlada corrected it and just created a new annotated tag `2.3.5`.

So when you created the branch, the `--tags` approach worked correctly, but when Github actions annotated it (can't confirm it did so but assuming), that broke it [but in reality just put it to the standard upstream uses].

**Comment by AnatoleAM** [comment]
Ah alright. I'll merge this then and hopefully it's fine - this branch is temporary anyway it's only for testing the simulated v2 on the [new API](https://github.com/seventv/api).

**Comment by Felanbird** [comment]
Honestly I didn't fully look at what change your made relevant to the paints PR - I saw the :x: and immediately looked into what failed, not seeing that this wasn't fully necessary as you just stripped `pull-request:` from the file. 😁

**Comment by AnatoleAM** [comment]
Yeah it wasn't actually meant to touch that PR, that branch is just there because it's faster to use github ci than to spin up VMs for each system I'd want it to compile for

**Pull request merged**
