### PR TITLE
ci: use correct openssl location

### LINKED ISSUE #278: macOS Universal binary doesn't properly include openssl dependency
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

The macOS universal binary shipped with the current nightly build appears to be missing the openssl dependency in the actual release package, when opening on a system where openssl isn't installed using homebrew (which is needed for building yourself, but shouldn't be for running the shipped binary) the application crashes on launch:

image

<details><summary>Full error message</summary>
<p>

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               chatterino [30950]
Path:                  /private/var/folders/*/chatterino.app/Contents/MacOS/chatterino
Identifier:            app.7tv.chatterino7
Version:               7.5.1 (7.5.1)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-10-03 17:31:20.3709 +0200
OS Version:            macOS 14.5 (23F79)
Report Version:        12
Anonymous UUID:        8C03F0AF-4765-1858-DCD8-4DAB8DCDD03E

Sleep/Wake UUID:       21CDEA3E-DA5D-4699-981B-575766D2BFC6

Time Awake Since Boot: 1600000 seconds
Time Since Wake:       3681 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /opt/homebrew/*/libssl.3.dylib
Referenced from: <A0F143F0-EA1C-3172-90C2-AEB8F20EA5B9> /private/var/folders/*/chatterino.app/Contents/MacOS/chatterino
Reason: tried: '/opt/homebrew/*/libssl.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/*/libssl.3.dylib' (no such file), '/opt/homebrew/*/libssl.3.dylib' (no such file)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x1978a1a50 __abort_with_payload + 8
1   dyld                          	       0x1978ac628 abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x1978ac65c abort_with_payload + 16
3   dyld                          	       0x19783e6b0 dyld4::halt(char const*, dyld4::StructuredError const*) + 304
4   dyld                          	       0x19783b258 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3888
5   dyld                          	       0x197839edc start + 1844

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016fbea850   x3: 0x00000000000000dd
    x4: 0x000000016fbea450   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000020   x9: 0x000000016fbea3c6  x10: 0x000000000000000a  x11: 0x0000000000000000
   x12: 0x0000000000000033  x13: 0x1000000000000000  x14: 0x0000000000000004  x15: 0x0000000000008000
   x16: 0x0000000000000209  x17: 0x000000019783737c  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016fbea450  x21: 0x00000000000000dd  x22: 0x000000016fbea850  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x0000000000000001  x26: 0x000000016fbeb208  x27: 0x0000000000000101
   x28: 0x000000016fbeb2c8   fp: 0x000000016fbea420   lr: 0x00000001978ac628
    sp: 0x000000016fbea3e0   pc: 0x00000001978a1a50 cpsr: 0x80001000
   far: 0x0000000000000000  esr: 0x56000080  Address size fault

Binary Images:
       0x101d4c000 -        0x1021b3fff org.qt-project.QtWidgets (6.7) <45c6fa47-828c-3696-b36e-c66fa5142918> /private/var/folders/*/chatterino.app/Contents/Frameworks/QtWidgets.framework/Versions/A/QtWidgets
       0x10122c000 -        0x101273fff org.qt-project.QtSvg (6.7) <38c2595e-88d3-33cc-9077-7aa2eb6bd6e6> /private/var/folders/*/chatterino.app/Contents/Frameworks/QtSvg.framework/Versions/A/QtSvg
       0x10129c000 -        0x1018ebfff org.qt-project.QtGui (6.7) <55116b9a-f5b8-3468-807f-78bdf504c474> /private/var/folders/*/chatterino.app/Contents/Frameworks/QtGui.framework/Versions/A/QtGui
       0x10116c000 -        0x10116ffff org.qt-project.QtConcurrent (6.7) <3710d338-fb2c-3569-a42d-a7727912515b> /private/var/folders/*/chatterino.app/Contents/Frameworks/QtConcurrent.framework/Versions/A/QtConcurrent
       0x10231c000 -        0x10243ffff org.qt-project.QtNetwork (6.7) <e87cabc4-7da0-322a-9e5b-3bd1b6a7bceb> /private/var/folders/*/chatterino.app/Contents/Frameworks/QtNetwork.framework/Versions/A/QtNetwork
       0x101bd0000 -        0x101c7ffff org.qt-project.QtCore5Compat (6.7) <9d948618-2c29-359d-b443-bd6fc75c57ac> /private/var/folders/*/chatterino.app/Contents/Frameworks/QtCore5Compat.framework/Versions/A/QtCore5Compat
       0x10302c000 -        0x1034d7fff org.qt-project.QtCore (6.7) <1927f3a6-4509-37e6-9308-9ed6fa957d67> /private/var/folders/*/chatterino.app/Contents/Frameworks/QtCore.framework/Versions/A/QtCore
       0x100214000 -        0x100b47fff app.7tv.chatterino7 (7.5.1) <a0f143f0-ea1c-3172-90c2-aeb8f20ea5b9> /private/var/folders/*/chatterino.app/Contents/MacOS/chatterino
       0x197834000 -        0x1978bca17 dyld (*) <37bbc384-0755-31c7-a808-0ed49e44dd8e> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 28
    thread_create: 0
    thread_set_state: 404

VM Region Summary:
ReadOnly portion of Libraries: Total=564.9M resident=0K(0%) swapped_out_or_unallocated=564.9M(100%)
Writable regions: Total=12.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=12.3M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE                         16K        1 
__DATA                             395K       12 
__DATA_CONST                       775K        9 
__DATA_DIRTY                         7K        1 
__LINKEDIT                       537.6M        9 
__TEXT                            27.3M        9 
dyld private memory               4384K        4 
===========                     =======  ======= 
TOTAL                            634.3M       47 

-----------
Full Report
-----------

{"app_name":"chatterino","timestamp":"2024-10-03 17:31:20.00 +0200","app_version":"7.5.1","slice_uuid":"a0f143f0-ea1c-3172-90c2-aeb8f20ea5b9","build_version":"7.5.1","platform":1,"bundleID":"app.7tv.chatterino7","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 14.5 (23F79)","roots_installed":0,"name":"chatterino","incident_id":"79F3F143-2526-456E-A23F-6EBF86EFB6F3"}
{
  "uptime" : 1600000,
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac15,6",
  "coalitionID" : 172301,
  "osVersion" : {
    "train" : "macOS 14.5",
    "build" : "23F79",
    "releaseType" : "User"
  },
  "captureTime" : "2024-10-03 17:31:20.3709 +0200",
  "codeSigningMonitor" : 1,
  "incident" : "79F3F143-2526-456E-A23F-6EBF86EFB6F3",
  "pid" : 30950,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-10-03 17:31:19.1322 +0200",
  "procStartAbsTime" : 38769199006073,
  "procExitAbsTime" : 38769228714652,
  "procName" : "chatterino",
  "procPath" : "\/private\/var\/folders\/*\/chatterino.app\/Contents\/MacOS\/chatterino",
  "bundleInfo" : {"CFBundleShortVersionString":"7.5.1","CFBundleVersion":"7.5.1","CFBundleIdentifier":"app.7tv.chatterino7"},
  "storeInfo" : {"deviceIdentifierForVendor":"CABE886B-7E53-5B37-97D7-A05EC68C74F9","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "app.7tv.chatterino7",
  "crashReporterKey" : "8C03F0AF-4765-1858-DCD8-4DAB8DCDD03E",
  "codeSigningID" : "app.7tv.chatterino7",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 570425857,
  "codeSigningValidationCategory" : 10,
  "codeSigningTrustLevel" : 4294967295,
  "instructionByteStream" : {"beforePC":"1AAAABABAAAYAQAAIAEAACgBAAAwAQAAOAEAAFQBAAAwQYDSARAA1A==","atPC":"AwEAVH8jA9X9e7+p\/QMAkQpV\/pe\/AwCR\/XvBqP8PX9bAA1\/WEC2A0g=="},
  "wakeTime" : 3681,
  "sleepWakeUUID" : "21CDEA3E-DA5D-4699-981B-575766D2BFC6",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: \/opt\/homebrew\/*\/libssl.3.dylib","Referenced from: <A0F143F0-EA1C-3172-90C2-AEB8F20EA5B9> \/private\/var\/folders\/*\/chatterino.app\/Contents\/MacOS\/chatterino","Reason: tried: '\/opt\/homebrew\/*\/libssl.3.dylib' (no such file), '\/System\/Volumes\/Preboot\/Cryptexes\/OS\/opt\/homebrew\/*\/libssl.3.dylib' (no such file), '\/opt\/homebrew\/*\/libssl.3.dylib' (no such file)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":404,"task_for_pid":28},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":50310370,"threadState":{"x":[{"value":6},{"value":1},{"value":6169733200},{"value":221},{"value":6169732176},{"value":0},{"value":0},{"value":0},{"value":32},{"value":6169732038},{"value":10},{"value":0},{"value":51},{"value":1152921504606846976},{"value":4},{"value":32768},{"value":521},{"value":6836941692,"symbolLocation":416,"symbol":"__simple_bprintf"},{"value":0},{"value":0},{"value":6169732176},{"value":221},{"value":6169733200},{"value":1},{"value":6},{"value":1},{"value":6169735688},{"value":257},{"value":6169735880}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6837421608},"cpsr":{"value":2147487744},"fp":{"value":6169732128},"sp":{"value":6169732064},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6837377616,"matchesCrashFrame":1},"far":{"value":0}},"frames":[{"imageOffset":449104,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":8},{"imageOffset":493096,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":104,"imageIndex":8},{"imageOffset":493148,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":8},{"imageOffset":42672,"symbol":"dyld4::halt(char const*, dyld4::StructuredError const*)","symbolLocation":304,"imageIndex":8},{"imageOffset":29272,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3888,"imageIndex":8},{"imageOffset":24284,"symbol":"start","symbolLocation":1844,"imageIndex":8}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4325687296,
    "CFBundleShortVersionString" : "6.7",
    "CFBundleIdentifier" : "org.qt-project.QtWidgets",
    "size" : 4620288,
    "uuid" : "45c6fa47-828c-3696-b36e-c66fa5142918",
    "path" : "\/private\/var\/folders\/*\/chatterino.app\/Contents\/Frameworks\/QtWidgets.framework\/Versions\/A\/QtWidgets",
    "name" : "QtWidgets",
    "CFBundleVersion" : "6.7.1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4314021888,
    "CFBundleShortVersionString" : "6.7",
    "CFBundleIdentifier" : "org.qt-project.QtSvg",
    "size" : 294912,
    "uuid" : "38c2595e-88d3-33cc-9077-7aa2eb6bd6e6",
    "path" : "\/private\/var\/folders\/*\/chatterino.app\/Contents\/Frameworks\/QtSvg.framework\/Versions\/A\/QtSvg",
    "name" : "QtSvg",
    "CFBundleVersion" : "6.7.1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4314480640,
    "CFBundleShortVersionString" : "6.7",
    "CFBundleIdentifier" : "org.qt-project.QtGui",
    "size" : 6619136,
    "uuid" : "55116b9a-f5b8-3468-807f-78bdf504c474",
    "path" : "\/private\/var\/folders\/*\/chatterino.app\/Contents\/Frameworks\/QtGui.framework\/Versions\/A\/QtGui",
    "name" : "QtGui",
    "CFBundleVersion" : "6.7.1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4313235456,
    "CFBundleShortVersionString" : "6.7",
    "CFBundleIdentifier" : "org.qt-project.QtConcurrent",
    "size" : 16384,
    "uuid" : "3710d338-fb2c-3569-a42d-a7727912515b",
    "path" : "\/private\/var\/folders\/*\/chatterino.app\/Contents\/Frameworks\/QtConcurrent.framework\/Versions\/A\/QtConcurrent",
    "name" : "QtConcurrent",
    "CFBundleVersion" : "6.7.1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4331782144,
    "CFBundleShortVersionString" : "6.7",
    "CFBundleIdentifier" : "org.qt-project.QtNetwork",
    "size" : 1196032,
    "uuid" : "e87cabc4-7da0-322a-9e5b-3bd1b6a7bceb",
    "path" : "\/private\/var\/folders\/*\/chatterino.app\/Contents\/Frameworks\/QtNetwork.framework\/Versions\/A\/QtNetwork",
    "name" : "QtNetwork",
    "CFBundleVersion" : "6.7.1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4324130816,
    "CFBundleShortVersionString" : "6.7",
    "CFBundleIdentifier" : "org.qt-project.QtCore5Compat",
    "size" : 720896,
    "uuid" : "9d948618-2c29-359d-b443-bd6fc75c57ac",
    "path" : "\/private\/var\/folders\/*\/chatterino.app\/Contents\/Frameworks\/QtCore5Compat.framework\/Versions\/A\/QtCore5Compat",
    "name" : "QtCore5Compat",
    "CFBundleVersion" : "6.7.1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4345479168,
    "CFBundleShortVersionString" : "6.7",
    "CFBundleIdentifier" : "org.qt-project.QtCore",
    "size" : 4898816,
    "uuid" : "1927f3a6-4509-37e6-9308-9ed6fa957d67",
    "path" : "\/private\/var\/folders\/*\/chatterino.app\/Contents\/Frameworks\/QtCore.framework\/Versions\/A\/QtCore",
    "name" : "QtCore",
    "CFBundleVersion" : "6.7.1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4297146368,
    "CFBundleShortVersionString" : "7.5.1",
    "CFBundleIdentifier" : "app.7tv.chatterino7",
    "size" : 9650176,
    "uuid" : "a0f143f0-ea1c-3172-90c2-aeb8f20ea5b9",
    "path" : "\/private\/var\/folders\/*\/chatterino.app\/Contents\/MacOS\/chatterino",
    "name" : "chatterino",
    "CFBundleVersion" : "7.5.1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6836928512,
    "size" : 559640,
    "uuid" : "37bbc384-0755-31c7-a808-0ed49e44dd8e",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 6836174848,
  "size" : 4220698624,
  "uuid" : "3406ad1b-2469-30eb-9863-5dce861e6dea"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=564.9M resident=0K(0%) swapped_out_or_unallocated=564.9M(100%)\nWritable regions: Total=12.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=12.3M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                         16K        1 \n__DATA                             395K       12 \n__DATA_CONST                       775K        9 \n__DATA_DIRTY                         7K        1 \n__LINKEDIT                       537.6M        9 \n__TEXT                            27.3M        9 \ndyld private memory               4384K        4 \n===========                     =======  ======= \nTOTAL                            634.3M       47 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "15660515bfec7d60cf3793af2c43d43898e6ef58",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "63508950b3714d3622fc77f7",
      "factorPackIds" : {
        "SIRI_MEMORY_SYNC_CONFIG" : "6526e111d0c9ce2f459b54a8"
      },
      "deploymentId" : 240000015
    },
    {
      "rolloutId" : "648c94d4ebdf9e3e398fa708",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_NL_OVERRIDES" : "65a8104b6712a43e7922cab8"
      },
      "deploymentId" : 240000171
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "c47ab4cc-c9c3-4b5d-a87c-e2433ce02597",
      "experimentId" : "6639bc6ba73d460582162323",
      "deploymentId" : 400000006
    },
    {
      "treatmentId" : "45f4e2a5-551b-4bc2-a2dc-19c244dda8f8",
      "experimentId" : "6643969b3099cf28e049862f",
      "deploymentId" : 400000007
    }
  ]
}
}

Model: Mac15,6, BootROM 10151.121.1, proc 11:5:6 processors, 18 GB, SMC 
Graphics: Apple M3 Pro, Apple M3 Pro, Built-In
Display: Color LCD, 3024 x 1964 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4388), wl0: Apr  4 2024 20:57:11 version 23.30.58.0.41.51.138 FWID 01-baea9d27
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

</p>
</details> 

This error is only present in the chatterino7 binary, chatterino2 works fine (I assume some differences in the build process since iirc the c2 universal binary is built on pajladas Mac Mini now)

### Screenshots

_No response_

### OS and Chatterino Version

Chatterino 7 nightly, commit fb35be0

### PR DESCRIPTION
**Pull request by Nerixyz**
Fixes #278.

### CODE REVIEW

**Comment by LosFarmosCTL** [comment]
Looks like the arm64 part of the binary links to the absolute homebrew paths, while x86 correctly uses the framework folder relative to the execution path. Not exactly sure what causes that to happen though:

SCR-20241003-pubs

**Comment by Nerixyz** [comment]
@LosFarmosCTL could you try the universal build from this PR? https://github.com/SevenTV/chatterino7/actions/runs/11166845955?pr=279

**Comment by LosFarmosCTL** [comment]
Yup, it works again using the substitution. 

Still no idea why it's not getting set correctly in the first place, I tried poking around locally the last two hours but couldn't find any fix. The macdeployqt call in .CI/MacDeploy.sh doesn't rewrite the paths correctly, but why it's only an issue for specifically libssl in the arm64 part is beyond me, since everything else does get set correctly. Looks like changing the install name afterwards is the best fix for the moment.

**Comment by Nerixyz** [comment]
Thank you! As far as I know, pajlada only used the fixes I had before this PR (for rewriting libssl's search paths), not sure why more adjustments are required now. I'm hoping Chatterino2 can use this in the future as well (would make the release process a bit more "open").

**Pull request merged**
